#!/usr/bin/env ruby
#
# Scrapboxページ内のGyazo行を取得し、Scrapbox情報をGyazoページに書き出す
#
# % addgss project page
# % addgss CosenseのJSONファイル
#

require 'gyazo'
require 'json'
require 'cgi'

access_token = ENV['GYAZO_TOKEN'] # アクセストークン: .bash_profileに書いている
gyazo = Gyazo::Client.new access_token: access_token

#  
# Gyazo gemに登録されていないAPI追加
#
module Gyazo
  class Client
    def set_desc(image_id:, desc: desc) # descの書き換え
      path = "/api/images/#{image_id}"

      res = @conn.patch path do |req| # patchというのを使う
        req.body = {
          access_token: @access_token,
          desc: desc.to_s
        }
        req.headers['User-Agent'] = @user_agent
      end
      # raise Gyazo::Error, res.body unless res.status == 200
    end

    def get_desc(image_id:) # descの取得
      res = image image_id: image_id
      return res[:metadata] ? res[:metadata][:desc] : ''
    end
  end
end

#
# Gyazoデータにdescに一行追加
#
def process(gyazo, id, new_line)
  desc = gyazo.get_desc image_id:id
  desclines = desc.split
  if desclines.include?(new_line)
    STDERR.puts "Scrapbox情報はGyazoページ(#{id})に登録ずみです"
    STDERR.puts "https://Gyazo.com/#{id}"
  else
    desclines.push(new_line)
    gyazo.set_desc image_id:id, desc:desclines.join("\n")
    STDERR.puts "https://Gyazo.com/#{id} にScrapboxページの情報を登録しました"
  end
end

if !ARGV[0]
  STDERR.puts "Scrapboxページ内のGyazo行を調べ、Gyazoデータに反映させる"
  STDERR.puts "% addgss page [project]"
  STDERR.puts "% addgss project.json"
  exit
end

config = {
  project: 'GSS'
}
config_file = File.expand_path("~/.gss")

if !File.exist?(config_file)
  f = File.open(config_file,"w")
  f.puts config.to_json
else
  config = JSON.parse(File.read(config_file))
end


project = ''
jsonfile = false
if ARGV[0] =~ /\.json$/
  jsonfile = ARGV[0]
else
  page = ARGV[0]
  project = ARGV[1]
  if project
    config['project'] = project
    File.open(config_file,"w"){ |f|
      f.puts config.to_json
    }
  end
  config = JSON.parse(File.read(config_file))
  project = config['project'] unless project
end

skipid = 'fa86eb51d0779e5fb02abb'
skipid = 'be475abebd8fcdc22ffb90c55d75cb66'
skipid = 'd862'
skip = true

if jsonfile
  begin
    json = JSON.parse(File.read(jsonfile))
  rescue
    STDERR.puts "#{jsonfile} not found"
    exit
  end
  project = json['name']
  lines = 0
  json['pages'].each { |page|
    puts page['title']
    puts project
    page['lines'].each { |line|
      path = "https://scrapbox.io/#{project}/#{page['title']}".gsub(' ','%20')
      # Scrapboxページのテキストから gyazoデータを探し、そのGyazoページのコメント(desc)を取得
      while line.sub!(/gyazo.com\/([0-9a-f]+)/i,'') do
        id = $1
        puts "#{id} #{path}"

        process(gyazo, id, path) unless skip
        
        if id == skipid
          skip = false
        end
      end
    }
  }
else
  #
  # privateなプロジェクト読み出しのためのCookie取得
  # Cookieはsidコマンドで取得できるようにしておく
  #
  sid = `sid`.chomp
  
  #
  # Scrapboxページ読み出し
  #
  pagee = page.gsub(' ','%20')
  pagee = pagee.gsub('/','%2f')
  # pagee = CGI.escape(pagee) # "/" などをエスケープ

  # ScrapboxのAPIを使うのが面倒なのでwgetでテキストを取得
  res = `wget -q -O - --header 'cookie: connect.sid=#{sid}' \"https://scrapbox.io/api/pages/#{project}/#{pagee}/text\"`
  res.split.each { | line |
    while line.sub!(/gyazo.com\/([0-9a-fA-F]{32})/,'') do
      id = $1
      new_line = "https://scrapbox.io/#{project}/#{pagee}"
      process(gyazo, id, new_line)
    end
  }
end

