#!/usr/bin/env ruby
#
# GSS - Gyazo/Scrapbox Search
#
# % gss キーワード [プロジェクト]
#

require 'gyazo'
require 'json'

#
# 検索対象プロジェクトは ~/.gss にセーブしておく
#
config_file = File.expand_path("~/.gss")
config = {
  project: 'GSS'
}

if !File.exist?(config_file)
  f = File.open(config_file,"w")
  f.puts config.to_json
else
  config = JSON.parse(File.read(config_file))
end

keyword = ARGV[0]
project = ARGV[1]

if !keyword
  STDERR.puts 'GSS - Gyazo/Scrapbox search'
  STDERR.puts 'Usage: % gss keyword [project]'
  exit
end

if project
  # projectが引数で指定されていた場合はセーブしておく
  config['project'] = project
  f = File.open(config_file,"w")
  f.puts config.to_json
else
  project = config['project']
end

module Gyazo
  class Client

    # Gyazo gemに検索APIが無いので追加する
    # 検索APIの仕様は以下に書かれている
    # https://gyazo.com/api/docs/search
    
    def search(query:query, page: 1, per: 20)
      res = @conn.get '/api/search' do |req|
        req.params[:access_token] = @access_token
        req.params[:query] = query
        req.params[:page] = page
        req.params[:per] = per
        # req.headers['User-Agent'] = @user_agent
      end

      raise Gyazo::Error, res.body unless res.status == 200
      return ::JSON.parse res.body, symbolize_names: true
    end
  end
end

gyazo_token = ENV['GYAZO_TOKEN'] # アクセストークン: .bash_profileに書いている

gyazo = Gyazo::Client.new access_token: gyazo_token

res = gyazo.search query: "#{keyword} #{project}", page:1, per:10

#
# 検索結果の表示
#
require "erb"
require "cgi"

template = <<~ERB
  <html>
    <body>
      <h1>「<%= keyword %>」検索結果 (<%= project %>)</h1>
      <% if res.length > 0 %>
        <ul>
          <% res.each do |page| %>
            <%
              cosensepages = []
              desc = page[:metadata][:desc]
              desc.split.each { |line|
                cosensepages.push(line) if line =~ /scrapbox.io/
              }
              cosensepage = ''
              cosensepages.each { |line|
                if line.length > cosensepage.length
                  cosensepage = line
                end
              }
            %>
            <li>
               <a href= "<%= cosensepage %>"><img src="<%= page[:thumb_url] %>"> </a>
               <ul>
                 <%
                   cosensepages.each { |cosensepage|
                 %>
                 <li><%= CGI.unescape(cosensepage) %></li>
                 <%
                 }
                 %>
               </ul>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>何もありません</p>
      <% end %>
    </body>
  </html>
ERB

File.open("/tmp/__gss.html","w"){ |f|
  f.puts ERB.new(template).result(binding)
}
system "open /tmp/__gss.html"
